# Memos :
#"PORT_HOTE:PORT_CONTENEUR"
#Ne pas insérer de virgule à la fin des lignes sous peine d'erreurs

services:
  
  #Projet front end
  frontPatientWebApp:
    image: frontpatient.webapp
    build:
      context: .
      dockerfile: FrontPatient.AspNetCore/Dockerfile
    ports:
      - "8086:8086"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8086
      ASPNETCORE_ENVIRONMENT: Development
      
  #Projet Ocelot
  ocelotWebapi:
    image: ocelotgatewayapi
    build:
      context: .
      dockerfile: OcelotGatewayApi/Dockerfile
    ports:
      - "8084:8084"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8084
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=postgresBackPatient;Port=5432;User Id=postgres;Password=P@ssword1234;Database=DbAuth;"
    volumes:
      - ./OcelotGatewayApi/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  #Projet BackPatient
  backPatientWebapi:
    image: backpatient.webapi
    build:
      context: .
      dockerfile: BackPatient.WebApi/Dockerfile
    ports:
      - "8082:8082"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8082
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=postgresBackPatient;Port=5432;User Id=postgres;Password=P@ssword1234;Database=DbPatient;"
    volumes:
      - ./BackPatient.WebApi/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  #Base de données MongoDB
  mongoNotesPatient:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password12345
    volumes:
      - mongo_data:/data/db

  #Interface admin MongoDB
  mongoNotesPatientExpress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:Password12345@mongoNotesPatient:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: P@ssword789
  
  # Base de données Postgresql   
  postgresBackPatient:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    # Force PostgreSQL à écouter sur toutes les adresses réseau
    command: [ "postgres", "-c", "listen_addresses=*" ]
    #Aficher les variables d'environnement reel :  docker compose exec postgresBackPatient env
    environment:
      POSTGRES_PASSWORD: P@ssword1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d
  
  # Interface Adminer Postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

#Definir les volumes 
volumes:
  pgdata:
  mongo_data:
