# Memos :
#"PORT_HOTE:PORT_CONTENEUR"
#Ne pas insérer de virgule à la fin des lignes sous peine d'erreurs

services:
  
  #Projet front end
  frontPatientWebApp:
    image: frontpatient.webapp
    build:
      context: .
      dockerfile: FrontPatient.AspNetCore/Dockerfile
    ports:
      - "8085:8085"
      - "8086:8086"
    environment:
      #https://0.0.0.0:8083;
      ASPNETCORE_URLS: http://0.0.0.0:8086
      # dotnet dev-certs https --clean
      # dotnet dev-certs https --export-path ./aspnetapp.pfx --password "P@ssword1234" ou dotnet dev-certs https --trust
      #ASPNETCORE_Kestrel__Certificates__Default__Password: P@ssword1234
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
  
  #Projet Ocelot
  ocelotWebapi:
    image: ocelotgatewayapi
    build:
      context: .
      dockerfile: OcelotGatewayApi/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"
    environment:
      #https://0.0.0.0:8083;
      ASPNETCORE_URLS: http://0.0.0.0:8084
      # dotnet dev-certs https --clean
      # dotnet dev-certs https --export-path ./aspnetapp.pfx --password "P@ssword1234" ou dotnet dev-certs https --trust
      #ASPNETCORE_Kestrel__Certificates__Default__Password: P@ssword1234
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./OcelotGatewayApi/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  #Projet BackPatient
  backPatientWebapi:
    image: backpatient.webapi
    build:
      context: .
      dockerfile: BackPatient.WebApi/Dockerfile
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      #https://0.0.0.0:8081;
      ASPNETCORE_URLS: http://0.0.0.0:8082
      # dotnet dev-certs https --clean
      # dotnet dev-certs https --export-path ./aspnetapp.pfx --password "P@ssword1234" ou dotnet dev-certs https --trust
      #ASPNETCORE_Kestrel__Certificates__Default__Password: P@ssword1234
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=postgresBackPatient;Port=5432;User Id=postgres;Password=P@ssword1234;Database=DbPatient;"
    volumes:
      - ./BackPatient.WebApi/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  
  # Base de données Postgresql   
  # Lancer ce service : docker compose up postgresBackPatient --remove-orphans
  postgresBackPatient:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    # Force PostgreSQL à écouter sur toutes les adresses réseau
    command: [ "postgres", "-c", "listen_addresses=*" ]
    #Aficher les variables d'environnement reel :  docker compose exec postgresBackPatient env
    environment:
      POSTGRES_PASSWORD: P@ssword1234
      POSTGRES_USER: postgres
      POSTGRES_DB: DbPatient
    volumes:
      - pgdata:/var/lib/postgresql
  
  # Interface Adminer Postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

#Definir les volumes 
volumes:
  pgdata:
